# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peerloan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('balance', models.FloatField()),
                ('on_hold_amt', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminMemo',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('model', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=50)),
                ('no', models.IntegerField()),
                ('content', models.CharField(max_length=200)),
                ('updated_by', models.CharField(max_length=100)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('ref_id', models.IntegerField()),
                ('model', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=3000, null=True)),
                ('by', models.CharField(max_length=50)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('amount', models.FloatField()),
                ('prod_id', models.IntegerField()),
                ('usr_id', models.IntegerField()),
                ('ref_num', models.CharField(max_length=45)),
                ('repaid_month', models.IntegerField()),
                ('instalment_lender', models.FloatField()),
                ('instalment_borrower', models.FloatField()),
                ('verify_identity', models.CharField(max_length=45, null=True)),
                ('detail_info', models.CharField(max_length=3000)),
                ('status', models.CharField(max_length=45)),
                ('draw_down_date', models.DateTimeField(null=True)),
                ('expected_end_date', models.DateTimeField(null=True)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRequestDocument',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bor_id', models.IntegerField()),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('detail', models.CharField(max_length=45)),
                ('confirm', models.CharField(default=b'F', max_length=45)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('prod_id', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('usable_amount', models.FloatField()),
                ('used_amount', models.FloatField()),
                ('on_hold_amount', models.FloatField()),
                ('max_amount_per_loan', models.FloatField()),
                ('option', models.CharField(max_length=45)),
                ('ack', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=50)),
                ('debit', models.FloatField(null=True)),
                ('credit', models.FloatField(null=True)),
                ('balance', models.FloatField()),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('inv_id', models.IntegerField()),
                ('bor_id', models.IntegerField()),
                ('ref_num', models.CharField(max_length=45)),
                ('initial_amount', models.FloatField()),
                ('total_repay_amount_lender', models.FloatField()),
                ('total_repay_amount_borrower', models.FloatField()),
                ('instalment_lender', models.FloatField()),
                ('instalment_borrower', models.FloatField()),
                ('remain_principal', models.FloatField()),
                ('remain_principal_lender', models.FloatField()),
                ('remain_interest_lender', models.FloatField()),
                ('remain_interest_borrower', models.FloatField()),
                ('overdue_principal', models.FloatField()),
                ('overdue_interest', models.FloatField()),
                ('paid_overdue_interest', models.FloatField()),
                ('status', models.CharField(max_length=45)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('bor_id', models.IntegerField()),
                ('tenor', models.IntegerField()),
                ('instalment', models.FloatField()),
                ('principal', models.FloatField()),
                ('interest', models.FloatField()),
                ('instalment_l', models.FloatField()),
                ('principal_l', models.FloatField()),
                ('interest_l', models.FloatField()),
                ('due_date', models.CharField(max_length=50)),
                ('overdue_day', models.IntegerField()),
                ('overdue_interest', models.FloatField()),
                ('collection_fees', models.FloatField()),
                ('received_amount', models.FloatField(null=True)),
                ('repayment_method', models.CharField(max_length=50)),
                ('repayment_date', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyPortfolioSummary',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('details', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='OTPMessage',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('sequence', models.CharField(max_length=10)),
                ('mobile_no', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('generated_timestamp', models.DateTimeField()),
                ('expiring_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name_en', models.CharField(max_length=45)),
                ('name_zh', models.CharField(max_length=45)),
                ('repayment_period', models.IntegerField()),
                ('min_amount_per_loan', models.FloatField()),
                ('total_amount', models.FloatField()),
                ('min_amount', models.FloatField()),
                ('flat_rate_lender', models.FloatField()),
                ('flat_rate_borrower', models.FloatField()),
                ('APR_lender', models.FloatField()),
                ('APR_borrower', models.FloatField()),
                ('repayment_plan', models.CharField(max_length=45)),
                ('detail_info', models.CharField(max_length=3000)),
                ('required_docs', models.CharField(max_length=1000)),
                ('status', models.CharField(max_length=45)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('email', models.CharField(max_length=45)),
                ('mobile', models.CharField(max_length=45, null=True)),
                ('password', models.CharField(max_length=45)),
                ('receive_promotion', models.CharField(max_length=45)),
                ('detail_info', models.CharField(max_length=3000)),
                ('notification', models.CharField(max_length=3000, null=True)),
                ('type', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('info_type', models.CharField(max_length=45)),
                ('section', models.CharField(max_length=45)),
                ('details', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='UserOperationHistory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('type', models.CharField(max_length=45)),
                ('details', models.CharField(max_length=3000)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserOperationRequest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('type', models.CharField(max_length=45)),
                ('details', models.CharField(max_length=3000)),
                ('status', models.CharField(max_length=45)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('usr_id', models.IntegerField()),
                ('type', models.CharField(max_length=45)),
                ('amount_in', models.FloatField()),
                ('amount_out', models.FloatField()),
                ('source_usr_id', models.IntegerField(null=True)),
                ('destination_usr_id', models.IntegerField(null=True)),
                ('internal_ref', models.CharField(max_length=45)),
                ('cust_ref', models.CharField(max_length=45)),
                ('href', models.CharField(max_length=100, null=True)),
                ('create_timestamp', models.DateTimeField()),
                ('update_timestamp', models.DateTimeField()),
            ],
        ),
    ]
