"""
Django settings for project_peerloan project.

Generated by 'django-admin startproject' using Django 1.8.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
from django.utils.translation import ugettext_lazy as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'c^1kb0+)4#u*h$9405w2i3+o9p&=-80rs-@k#(ajk5px9$9f(y'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# security setting
#SECURE_SSL_REDIRECT = True

# set maintenance mode
# MAINTENANCE_MODE = False

# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'rest_framework',
    'captcha',
    'google_analytics',
    # 'maintenancemode',
    'peerloan',
)

CAPTCHA_IMAGE_SIZE = (100, 32)
CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_digit_challenge'

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
    	'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer',
    )
}

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'maintenancemode.middleware.MaintenanceModeMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'project_peerloan.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.core.context_processors.i18n',
            ],
        },
    },
]

WSGI_APPLICATION = 'project_peerloan.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'peerloan',
		'USER': 'root',
		'PASSWORD': 'bitnami',
		'HOST': '127.0.0.1',
		'PORT': '3306', 
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Hong_Kong'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# list of languages used
LANGUAGES = [
    ( 'en', _('English') ),
    ( 'zh', _('Traditional Chinese') ),
]

# directory that will host po and mo files
LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

# Email settings
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_HOST_USER = 'cs@zwap.hk'
EMAIL_HOST_PASSWORD = 'peerloan123'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'cs@zwap.hk'

# Twilio Account Information
TWILIO_ACCOUNT_SID = "ACb7c366a200aa5190530e128f46561915"
TWILIO_AUTH_TOKEN = "c9287069a0ddd57109273330a0f5e973"

# Friendly Score Information
FRIENDLY_SCORE_CLIENT_ID = "293_52jb53pwvbswcow0w4wog4448oss4w84s8kccowococg4gk0cw"
FRIENDLY_SCORE_CLIENT_SECRET = "5nwipkst7rk80cskok084gk4sw0kgs40ck8kgckscsg48wwg0w"

# Google Analytics
GOOGLE_ANALYTICS = {
    'google_analytics_id': '',
}

# Others
